---
title: "Project2"
author: "Gabriella Dauber"
date: "11/12/2021"
output: html_document
---

```{r}

##### Conditional #####

cbp1 <- c("midnightblue", "limegreen", "#E7B800", "deeppink1", "#00AFBB")

genretest <- function(genre.label){
  songs <- switch(genre.label,
                  "midnightblue" = "big room",
                  "limegreen" = "edm",
                  "#E7B800" = "hip hop & rap",
                  "deeppink1" = "latin & reggaeton",
                  "#00AFBB" = "pop"
                  )
  return(songs)
}
genretest("limegreen")
genretest("deeppink1")
```

##### Loop #####

```{r}

colors_to_genres <- rep(NA, length(cbp1))
for (k in 1:length(cbp1)){
  colors_to_genres[k] <- genretest(cbp1[k])
}

colors_to_genres

```

```{r}

##### function #####

library(ggplot2)
top50 <- read.csv("top50cleanspotify.csv", encoding = "Windows-1252")
cbp1 <- c("midnightblue", "limegreen", "#E7B800", "deeppink1", "#00AFBB")

spotify.plot <- function(xpos, ypos){
  ggplot(top50, aes_string(x = xpos, y = ypos, color = "Genre", fill = "Genre")) + geom_point(size = 3) + xlab(sub("[.]", " ", xpos)) + ylab(sub("[.]", " ", ypos)) + scale_colour_manual(values=cbp1)
}

spotify.plot("Popularity", "Danceability")

```

```{r}

##### function #####

library(ggplot2)
top50 <- read.csv("top50cleanspotify.csv", encoding = "Windows-1252")
cbp1 <- c("midnightblue", "limegreen", "#E7B800", "deeppink1", "#00AFBB")

spotify.plot("Energy", "Beats.Per.Minute")

```
```{r}

####### IGNORE EVERYTHING BELOW THIS SCRIPT (practice) ######

```

```{r}
#Conditional

cpb2 <- c("pop", "latin & reggaeton", "hip hop & rap", "edm", "big room")

artist.test <- function(artist.label){
  artist <- switch(artist.label,
                   "pop" = "Shawn Mendes", "Ariana Grande",
                   "latin & reggaeton" = "Anuel AA", 
                   "hip hop & rap" = "Post Malone", 
                   "edm" = "The Chainsmokers", 
                   "big room" = "Martin Garrix"
                   )
  return(artist)
}

artist.test("pop")
artist.test("edm")

```

```{r}
#Conditional 

top50 <- read.csv("top50cleanspotify.csv", encoding = "Windows-1252")
data <- top50

ifelse(top50$Beats.Per.Minute > 100, "Get up and dance!", "Don't dance")
ifelse(top50$Beats.Per.Minute[2] > 100, "Get up and dance!", "Don't dance")
ifelse(top50$Beats.Per.Minute[3] > 100, "Get up and dance!", "Don't dance")
ifelse(top50$Beats.Per.Minute[4] > 100, "Get up and dance!", "Don't dance")
ifelse(top50$Beats.Per.Minute[5] > 100, "Get up and dance!", "Don't dance")
ifelse(top50$Beats.Per.Minute[6] > 100, "Get up and dance!", "Don't dance")
ifelse(top50$Beats.Per.Minute[7] > 100, "Get up and dance!", "Don't dance")
ifelse(top50$Beats.Per.Minute[8] > 100, "Get up and dance!", "Don't dance")

```

```{r}
#Conditional  

top50 <- read.csv("top50cleanspotify.csv", encoding = "Windows-1252")
data <- top50

ifelse(top50$Danceability > 70, "Dance", "Don't dance") 
ifelse(top50$Beats.Per.Minute > 100, "Dance", "Don't dance")

if(top50$Danceability > 70) {
  print("Dance")
}

switch(top50$Danceability > 70
       )

```

```{r}
library(ggplot2)
top50 <- read.csv("top50cleanspotify.csv", encoding = "Windows-1252")
str(top50)

top50$Pop.bin <- ifelse(top50$Popularity >= 85, "green", "blue")

spotify.plot <- function(xpos, ypos){
  ggplot(top50, aes_string(x = xpos, y = ypos, color = "Pop.bin")) + geom_point(size = 3) + xlab(sub("[.]", " ", xpos)) + ylab(sub("[.]", " ", ypos)) 
}

spotify.plot("Popularity", "Danceability")
```

